services:
  - type: web
    name: aldamanalmahdod
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -c "import os; port = int(os.environ.get('PORT', 8000)); import uvicorn; uvicorn.run('main:app', host='0.0.0.0', port=port)"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
